config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :articles

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def create
    ## this is a cool inspection thing to have handy
    ## render plain: params[:article].inspect

    ## fails because of ForbiddenAttributesError
    ## @article = Article.new(params[:article])
    @article = Article.new(article_params) 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end

  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
    
    <% if @article.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count, "error") %> prohibited
                this article from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    
    <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </p>
    
    <p>
        <%= form.submit %>
    </p>
    
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

<%  if user_signed_in? %>
    <h3>current user : <%= current_user.email %></h3>
<% end %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
    </tr>
    
    <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'New article', new_article_path %>
</br>
<%= link_to 'Back -> Welcome', welcome_index_path %>

<%  if user_signed_in? %>
    <h3>current user : <%= current_user.email %></h3>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

<%  if user_signed_in? %>
    <h3>current user : <%= current_user.email %></h3>
<% end %>

app/views/articles/show.html.erb
<h1>Show Article</h1>

<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

<%  if user_signed_in? %>
    <h3>current user : <%= current_user.email %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- devise recommends -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome <%= current_user.email %></h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<h2>Hello universe!</h2>

<a href="/articles">Articles#Index</a>
</br>
<%= link_to 'My Blog - Articles#index', controller: 'articles' %>


<%  if user_signed_in? %>
    <h3>current user : <%= current_user.email %></h3>
<% end %>

<%= link_to "Log out", destroy_user_session_path, :method => :delete %>